import uuid
from datetime import date, datetime, time

from sqlalchemy import Column, Date, ForeignKey, Time
from sqlmodel import Field, SQLModel

from app.models.base import tz_column, utcnow

# Bit 0 = Monday … bit 6 = Sunday, matching Python's `date.weekday()`. A bitmask rather than
# seven booleans or a join table: "weekdays" is one integer, it compares in one operation,
# and the set of days is fixed forever.
ALL_DAYS = 0b1111111
WEEKDAYS = 0b0011111
WEEKENDS = 0b1100000


class Schedule(SQLModel, table=True):
    """A window during which a device plays something other than its default playlist.

    Schedules are an **override layer, not a replacement**: `Device.playlist_id` remains what
    a screen plays normally, and a schedule only takes over while its window is open. A
    device with no matching schedule right now falls back to its default, which means adding
    a schedule can never leave a screen with nothing to show.
    """

    __tablename__ = "schedules"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    account_id: uuid.UUID = Field(
        sa_column=Column(
            ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False, index=True
        )
    )
    device_id: uuid.UUID = Field(
        sa_column=Column(
            ForeignKey("devices.id", ondelete="CASCADE"), nullable=False, index=True
        )
    )
    # CASCADE, with a friendly 409 enforced in services/playlists.py before it can fire —
    # a schedule pointing at a playlist that no longer exists would be worse than the
    # schedule disappearing with it.
    playlist_id: uuid.UUID = Field(
        sa_column=Column(ForeignKey("playlists.id", ondelete="CASCADE"), nullable=False)
    )
    # Set when this row was generated by a Campaign (one schedule per device the campaign
    # targets, all sharing this id) rather than created directly. CASCADE so deleting the
    # campaign cleans up every schedule it produced without a separate sweep. Null means a
    # schedule created before Campaigns existed, or directly via this table's own API.
    campaign_id: uuid.UUID | None = Field(
        default=None,
        sa_column=Column(ForeignKey("campaigns.id", ondelete="CASCADE"), nullable=True, index=True),
    )

    name: str = Field(default="")
    days_of_week: int = Field(default=ALL_DAYS)

    # Local wall-clock time on the *device's* timezone, not the server's. TIME WITHOUT TIME
    # ZONE deliberately: "opens at 09:00" means 09:00 wherever the screen is, and storing an
    # offset here would freeze it against daylight saving.
    starts_at: time = Field(sa_column=Column(Time(timezone=False), nullable=False))
    ends_at: time = Field(sa_column=Column(Time(timezone=False), nullable=False))

    # Calendar-date bounds, both inclusive, both optional and independent of each other — a
    # campaign that should only run "from Sep 1 to Oct 15" without changing its daily window
    # or day-of-week pattern. Null on either end means unbounded in that direction, so an
    # ordinary recurring schedule (the overwhelming common case) is unaffected: both stay null
    # and every date check in scheduling.py short-circuits true. Dates, not datetimes, for the
    # same reason `starts_at`/`ends_at` are timezone-naive — evaluated against the device's own
    # local calendar date, not a fixed instant.
    start_date: date | None = Field(default=None, sa_column=Column(Date(), nullable=True))
    end_date: date | None = Field(default=None, sa_column=Column(Date(), nullable=True))
    # Optional time of day on each bound, same device-local wall clock: "from Sep 1 14:00 until
    # Oct 15 18:00". Each only means something alongside its date. Null keeps the bound where
    # it always was — midnight for the start, through the end of the day for the end.
    start_time: time | None = Field(default=None, sa_column=Column(Time(timezone=False), nullable=True))
    end_time: time | None = Field(default=None, sa_column=Column(Time(timezone=False), nullable=True))

    # Higher wins when windows overlap. Ties break toward the later `starts_at`, on the
    # reasoning that a window starting later is the more specific one.
    priority: int = Field(default=0)

    is_enabled: bool = Field(default=True)
    created_at: datetime = Field(default_factory=utcnow, sa_column=tz_column(nullable=False))
