<script setup lang="ts">
/**
 * The hero's centrepiece: the signage totem itself, in 3D, playing a loop.
 *
 * The chassis is a real STL (public/models/totem.stl, generated by tools/make_totem_stl.py).
 * STL carries no UVs, so the screen is a separate plane sitting a millimetre in front of the
 * panel's face, textured from a canvas this component redraws. Slides change every few
 * seconds with a cross fade, which is what the product does on a wall.
 *
 * It is deliberately cheap to run: one light rig, no shadows, no post processing, and the
 * render loop stops whenever the canvas is off screen or the tab is hidden. Anyone who has
 * asked for reduced motion gets a still frame and no rotation.
 */
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import * as THREE from 'three'
import { STLLoader } from 'three/examples/jsm/loaders/STLLoader.js'

import { SLIDES } from '@/data/slides'

/** Which slide is on air. Owned by the hero, so the CMS panel beside the totem can change it. */
const props = defineProps<{ active: number }>()

const FADE_MS = 700
/** The screen's pixel canvas. Its aspect decides how much of the panel the glass covers, so
 *  it is tuned to leave the same slab of black below the picture that a real totem has. */
const TEX_W = 600
const TEX_H = 1080

const host = ref<HTMLElement | null>(null)
const failed = ref(false)

let stop: (() => void) | null = null

onMounted(() => {
  const mount = host.value
  if (!mount) return
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches

  let renderer: THREE.WebGLRenderer
  try {
    renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true, powerPreference: 'low-power' })
  } catch {
    // No WebGL: the caller shows the still image instead.
    failed.value = true
    return
  }
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2))
  renderer.setSize(mount.clientWidth, mount.clientHeight, false)
  renderer.domElement.style.width = '100%'
  renderer.domElement.style.height = '100%'
  mount.appendChild(renderer.domElement)

  const scene = new THREE.Scene()
  // Framed so the whole totem, wheels included, sits inside the box with room to spare: at
  // this distance the visible height is about 2.6 units against a 2.2 unit model.
  const camera = new THREE.PerspectiveCamera(34, mount.clientWidth / mount.clientHeight, 0.1, 100)
  camera.position.set(1.3, 1.4, 4.0)
  camera.lookAt(0, 1.1, 0)

  // A key light, a cool fill from the left, and a soft ambient so the black chassis still reads.
  scene.add(new THREE.AmbientLight(0xffffff, 0.75))
  const key = new THREE.DirectionalLight(0xffffff, 2.1)
  key.position.set(3, 5, 4)
  scene.add(key)
  const fill = new THREE.DirectionalLight(0x8fd0ff, 1.1)
  fill.position.set(-4, 2, 2)
  scene.add(fill)
  // A rim from behind, so the black chassis keeps an edge against a dark blue page.
  const rim = new THREE.DirectionalLight(0xbfe3ff, 2.4)
  rim.position.set(-2.5, 3, -4)
  scene.add(rim)

  const group = new THREE.Group()
  scene.add(group)

  // --- The screen: a canvas redrawn on a timer, mapped onto a plane ------------------------
  const canvas = document.createElement('canvas')
  canvas.width = TEX_W
  canvas.height = TEX_H
  const ctx = canvas.getContext('2d')!
  const texture = new THREE.CanvasTexture(canvas)
  texture.colorSpace = THREE.SRGBColorSpace

  const images = new Map<string, HTMLImageElement>()
  for (const s of SLIDES) {
    if (!s.src) continue
    const img = new Image()
    img.crossOrigin = 'anonymous'
    img.src = s.src
    images.set(s.src, img)
  }

  function drawSlide(slide: (typeof SLIDES)[number], alpha: number) {
    ctx.save()
    ctx.globalAlpha = alpha
    if (slide.src) {
      const img = images.get(slide.src)
      if (img?.complete && img.naturalWidth) {
        // Cover: fill the screen, crop the overflow, same as the product's own fit.
        const scale = Math.max(TEX_W / img.naturalWidth, TEX_H / img.naturalHeight)
        const w = img.naturalWidth * scale
        const h = img.naturalHeight * scale
        ctx.drawImage(img, (TEX_W - w) / 2, (TEX_H - h) / 2, w, h)
      } else {
        ctx.fillStyle = '#0b1b3a'
        ctx.fillRect(0, 0, TEX_W, TEX_H)
      }
      ctx.fillStyle = 'rgba(0,0,0,0.38)'
      ctx.fillRect(0, TEX_H * 0.6, TEX_W, TEX_H * 0.4)
    } else {
      const g = ctx.createLinearGradient(0, 0, TEX_W, TEX_H)
      g.addColorStop(0, slide.from ?? '#002f96')
      g.addColorStop(1, slide.to ?? '#0076dd')
      ctx.fillStyle = g
      ctx.fillRect(0, 0, TEX_W, TEX_H)
    }
    ctx.textAlign = 'center'
    ctx.fillStyle = '#ffffff'
    ctx.font = `700 ${Math.round(TEX_W * 0.13)}px "Outfit Variable", Inter, sans-serif`
    ctx.fillText(slide.title, TEX_W / 2, TEX_H * 0.78, TEX_W * 0.88)
    ctx.fillStyle = 'rgba(255,255,255,0.75)'
    ctx.font = `400 ${Math.round(TEX_W * 0.055)}px Inter, sans-serif`
    ctx.fillText(slide.sub, TEX_W / 2, TEX_H * 0.85, TEX_W * 0.88)
    ctx.restore()
  }

  // `shown` is what is on the glass; `previous` is what it is fading out of.
  let shown = props.active
  let previous = props.active
  let changedAt = performance.now() - FADE_MS
  function paint(now: number) {
    const since = now - changedAt
    ctx.clearRect(0, 0, TEX_W, TEX_H)
    ctx.fillStyle = '#000'
    ctx.fillRect(0, 0, TEX_W, TEX_H)
    if (since < FADE_MS && !reduced && previous !== shown) {
      const t = since / FADE_MS
      drawSlide(SLIDES[previous], 1 - t)
      drawSlide(SLIDES[shown], t)
    } else {
      drawSlide(SLIDES[shown], 1)
    }
    texture.needsUpdate = true
  }
  paint(performance.now())

  const screen = new THREE.Mesh(
    new THREE.PlaneGeometry(1, 1),
    new THREE.MeshBasicMaterial({ map: texture, toneMapped: false }),
  )
  group.add(screen)

  // A dark surround a hair larger than the screen and a hair behind it. Without it a slide in
  // the brand blues sits on a light blue chassis against a blue band, and the glass stops
  // reading as glass.
  const bezelFrame = new THREE.Mesh(
    new THREE.PlaneGeometry(1, 1),
    new THREE.MeshBasicMaterial({ color: 0x07132b, toneMapped: false }),
  )
  group.add(bezelFrame)

  // --- The chassis --------------------------------------------------------------------------
  // Light blue, lightly metallic: it lifts off the dark band behind it instead of sinking into
  // it, and the rim light draws its edges brighter still. A high metalness would grey a pale
  // colour out, so most of the sheen comes from roughness rather than metal.
  const body = new THREE.MeshStandardMaterial({ color: 0x9fcbf5, roughness: 0.36, metalness: 0.28 })
  new STLLoader().load(
    '/models/totem.stl',
    (geometry) => {
      geometry.computeVertexNormals()
      geometry.computeBoundingBox()
      const bb = geometry.boundingBox!
      const size = new THREE.Vector3()
      bb.getSize(size)
      // The STL is in millimetres and stands on y = 0. Scale it to roughly 2.2 units tall and
      // centre it on the origin in x and z, leaving it standing on the floor.
      const scale = 2.2 / size.y
      geometry.translate(-(bb.min.x + size.x / 2), 0, -(bb.min.z + size.z / 2))
      geometry.scale(scale, scale, scale)
      const mesh = new THREE.Mesh(geometry, body)
      group.add(mesh)

      // Fit the screen plane to the panel's face: the same proportions the generator used.
      const PANEL_W = 900 * scale
      const PANEL_H = 1780 * scale
      const PANEL_Y = 160 * scale
      const PANEL_D = 64 * scale
      const bezel = PANEL_W * 0.045
      const w = PANEL_W - bezel * 2
      const h = w * (TEX_H / TEX_W)
      screen.scale.set(w, h, 1)
      // Hung from the top of the panel, leaving the lower slab dark, as the reference does.
      const cy = PANEL_Y + PANEL_H - h / 2 - bezel
      screen.position.set(0, cy, PANEL_D / 2 + 0.002)
      const pad = PANEL_W * 0.016
      bezelFrame.scale.set(w + pad * 2, h + pad * 2, 1)
      bezelFrame.position.set(0, cy, PANEL_D / 2 + 0.001)
    },
    undefined,
    () => { failed.value = true },
  )

  // --- The loop, paused whenever nobody can see it -------------------------------------------
  let raf = 0
  let visible = true
  const tick = (now: number) => {
    raf = requestAnimationFrame(tick)
    paint(now)
    if (!reduced) {
      // A slow turn, easing at the extremes so it never looks like a spinning product shot.
      group.rotation.y = Math.sin(now / 4200) * 0.42
    }
    renderer.render(scene, camera)
  }
  const start = () => { if (!raf) raf = requestAnimationFrame(tick) }
  const halt = () => { if (raf) { cancelAnimationFrame(raf); raf = 0 } }

  watch(() => props.active, (next) => {
    if (next === shown) return
    previous = shown
    shown = next
    changedAt = performance.now()
    start()
  })

  const io = new IntersectionObserver(([e]) => {
    visible = e.isIntersecting
    if (visible && !document.hidden) start()
    else halt()
  }, { threshold: 0.05 })
  io.observe(mount)

  const onVisibility = () => { if (document.hidden || !visible) halt(); else start() }
  document.addEventListener('visibilitychange', onVisibility)

  const onResize = () => {
    if (!mount.clientWidth) return
    camera.aspect = mount.clientWidth / mount.clientHeight
    camera.updateProjectionMatrix()
    renderer.setSize(mount.clientWidth, mount.clientHeight, false)
  }
  const ro = new ResizeObserver(onResize)
  ro.observe(mount)

  stop = () => {
    halt()
    io.disconnect()
    ro.disconnect()
    document.removeEventListener('visibilitychange', onVisibility)
    scene.traverse((o) => {
      const m = o as THREE.Mesh
      if (m.geometry) m.geometry.dispose()
      const mat = m.material as THREE.Material | THREE.Material[] | undefined
      if (Array.isArray(mat)) mat.forEach((x) => x.dispose())
      else mat?.dispose()
    })
    texture.dispose()
    renderer.dispose()
    renderer.domElement.remove()
  }
})

onBeforeUnmount(() => stop?.())
</script>

<template>
  <div class="relative aspect-[4/5] w-full sm:aspect-square">
    <!-- The floor it stands on: a soft ellipse of light, not a shadow map. -->
    <span
      class="pointer-events-none absolute inset-x-[12%] bottom-[8%] h-[12%] rounded-[50%] bg-black/45 blur-2xl"
      aria-hidden="true"
    />
    <div ref="host" class="size-full" role="img" aria-label="A Paskall signage totem playing a rotating loop" />
    <!-- No WebGL, or the model would not load: a still of the same thing. -->
    <img
      v-if="failed"
      src="/shots/screen-totem.webp"
      alt="A Paskall signage totem"
      class="absolute inset-0 m-auto h-full w-auto rounded-lg"
    />
  </div>
</template>
