"""playlist item has audio

Revision ID: 03bceec28343
Revises: 497215402ce2
Create Date: 2026-09-10 11:19:58.579614

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '03bceec28343'
down_revision: str | None = '497215402ce2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL on a table that may already hold rows — same two-step as trim_start_seconds in
    # 497215402ce2: add WITH a default so existing rows backfill, then drop the default so the
    # schema matches the model (env.py has compare_server_default=True).
    op.add_column(
        'playlist_items',
        sa.Column('has_audio', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('playlist_items', 'has_audio', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'has_audio')
    # ### end Alembic commands ###
