"""device platform

Revision ID: 0a1183f09b80
Revises: c4e8a1d2f7b3
Create Date: 2026-09-16 23:16:51.174412

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '0a1183f09b80'
down_revision: str | None = 'c4e8a1d2f7b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Every screen paired before this was the Android player, so the default is also the
    # honest backfill.
    op.add_column('devices', sa.Column('platform', sa.Enum('android', 'web', name='deviceplatform', native_enum=False), server_default='android', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'platform')
    # ### end Alembic commands ###
