"""schedule date range

Revision ID: 1265a01f0a12
Revises: 4ba9c18c599f
Create Date: 2026-09-14 08:59:12.150035

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '1265a01f0a12'
down_revision: str | None = '4ba9c18c599f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('schedules', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'end_date')
    op.drop_column('schedules', 'start_date')
    # ### end Alembic commands ###
