"""scene background

Revision ID: 2e4c09184e64
Revises: 32f7f8c96211
Create Date: 2026-09-17 08:56:30.835881

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '2e4c09184e64'
down_revision: str | None = '32f7f8c96211'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_items', sa.Column('background', sa.Enum('black', 'blur', name='scenebackground', native_enum=False), server_default='black', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'background')
    # ### end Alembic commands ###
