"""drop playlist item trim columns

Revision ID: 31c427eb08e7
Revises: 03bceec28343
Create Date: 2026-09-10 14:34:49.340804

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '31c427eb08e7'
down_revision: str | None = '03bceec28343'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'trim_end_seconds')
    op.drop_column('playlist_items', 'trim_start_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_items', sa.Column('trim_start_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('playlist_items', sa.Column('trim_end_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
