"""media stream copy

Revision ID: 32f7f8c96211
Revises: 0a1183f09b80
Create Date: 2026-09-17 07:50:58.731240

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '32f7f8c96211'
down_revision: str | None = '0a1183f09b80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('stream_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('media', sa.Column('stream_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('media', sa.Column('stream_checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('media', sa.Column('stream_mime', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('media', sa.Column('stream_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'stream_error')
    op.drop_column('media', 'stream_mime')
    op.drop_column('media', 'stream_checksum')
    op.drop_column('media', 'stream_size_bytes')
    op.drop_column('media', 'stream_key')
    # ### end Alembic commands ###
