"""playlist item elements scene model

Revision ID: 41a33957933f
Revises: ebb51f2a655b
Create Date: 2026-09-10 15:10:19.701080

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '41a33957933f'
down_revision: str | None = 'ebb51f2a655b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table('playlist_item_elements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('playlist_item_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('fit', sa.Enum('contain', 'cover', 'stretch', name='itemfit', native_enum=False), nullable=False),
    sa.Column('crop_x', sa.Float(), nullable=True),
    sa.Column('crop_y', sa.Float(), nullable=True),
    sa.Column('crop_zoom', sa.Float(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=False),
    sa.Column('rotation_degrees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['playlist_item_id'], ['playlist_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_item_elements_media_id'), 'playlist_item_elements', ['media_id'], unique=False)
    op.create_index(op.f('ix_playlist_item_elements_playlist_item_id'), 'playlist_item_elements', ['playlist_item_id'], unique=False)

    # Data migration, not just a schema change: every existing PlaylistItem was implicitly
    # "one full-bleed element" (the whole point of the old flat model). Backfill one
    # PlaylistItemElement per existing row, sized to the whole frame (x=0,y=0,w=1,h=1),
    # before the columns it's copied from are dropped below — gen_random_uuid() is built
    # into Postgres (no extension needed) since v13, and this repo runs 16.
    op.execute("""
        INSERT INTO playlist_item_elements
            (id, playlist_item_id, media_id, z_index, x, y, width, height,
             fit, crop_x, crop_y, crop_zoom, has_audio, rotation_degrees)
        SELECT gen_random_uuid(), id, media_id, 0, 0.0, 0.0, 1.0, 1.0,
               fit, crop_x, crop_y, crop_zoom, has_audio, rotation_degrees
        FROM playlist_items
    """)

    op.drop_index(op.f('ix_playlist_items_media_id'), table_name='playlist_items')
    op.drop_constraint(op.f('playlist_items_media_id_fkey'), 'playlist_items', type_='foreignkey')
    op.drop_column('playlist_items', 'rotation_degrees')
    op.drop_column('playlist_items', 'crop_zoom')
    op.drop_column('playlist_items', 'crop_x')
    op.drop_column('playlist_items', 'crop_y')
    op.drop_column('playlist_items', 'fit')
    op.drop_column('playlist_items', 'has_audio')
    op.drop_column('playlist_items', 'media_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_items', sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('playlist_items', sa.Column('has_audio', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('playlist_items', sa.Column('fit', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.add_column('playlist_items', sa.Column('crop_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('playlist_items', sa.Column('crop_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('playlist_items', sa.Column('crop_zoom', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('playlist_items', sa.Column('rotation_degrees', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('playlist_items_media_id_fkey'), 'playlist_items', 'media', ['media_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_playlist_items_media_id'), 'playlist_items', ['media_id'], unique=False)
    op.drop_index(op.f('ix_playlist_item_elements_playlist_item_id'), table_name='playlist_item_elements')
    op.drop_index(op.f('ix_playlist_item_elements_media_id'), table_name='playlist_item_elements')
    op.drop_table('playlist_item_elements')
    # ### end Alembic commands ###
