"""playlist item crop and video trim

Revision ID: 497215402ce2
Revises: d0b5419c0914
Create Date: 2026-09-09 16:59:17.536807

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '497215402ce2'
down_revision: str | None = 'd0b5419c0914'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('playlist_items', sa.Column('crop_x', sa.Float(), nullable=True))
    op.add_column('playlist_items', sa.Column('crop_y', sa.Float(), nullable=True))
    op.add_column('playlist_items', sa.Column('crop_zoom', sa.Float(), nullable=True))
    # NOT NULL on a table that may already hold rows — same two-step as
    # 9cfe71e36e53: add WITH a default so existing rows backfill, then drop the default so
    # the schema matches the model (env.py has compare_server_default=True).
    op.add_column(
        'playlist_items',
        sa.Column('trim_start_seconds', sa.Float(), nullable=False, server_default='0'),
    )
    op.alter_column('playlist_items', 'trim_start_seconds', server_default=None)
    op.add_column('playlist_items', sa.Column('trim_end_seconds', sa.Float(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'trim_end_seconds')
    op.drop_column('playlist_items', 'trim_start_seconds')
    op.drop_column('playlist_items', 'crop_zoom')
    op.drop_column('playlist_items', 'crop_y')
    op.drop_column('playlist_items', 'crop_x')
    # ### end Alembic commands ###
