"""device setting reported values

Revision ID: 4ba9c18c599f
Revises: 9343c6a18fd3
Create Date: 2026-09-11 11:35:07.917821

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '4ba9c18c599f'
down_revision: str | None = '9343c6a18fd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_settings', sa.Column('reported_value', sa.JSON(), nullable=True))
    op.add_column('device_settings', sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('device_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('device_settings', 'reported_at')
    op.drop_column('device_settings', 'reported_value')
    # ### end Alembic commands ###
