"""device settings

Revision ID: 514695584cc7
Revises: 6f514c2c6e96
Create Date: 2026-09-10 17:10:32.690847

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '514695584cc7'
down_revision: str | None = '6f514c2c6e96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_settings',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_settings')
    # ### end Alembic commands ###
