"""campaigns

Revision ID: 6f514c2c6e96
Revises: 41a33957933f
Create Date: 2026-09-10 15:44:57.313135

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '6f514c2c6e96'
down_revision: str | None = '41a33957933f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_table('campaign_devices',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'device_id')
    )
    op.add_column('schedules', sa.Column('campaign_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_schedules_campaign_id'), 'schedules', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'schedules', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_index(op.f('ix_schedules_campaign_id'), table_name='schedules')
    op.drop_column('schedules', 'campaign_id')
    op.drop_table('campaign_devices')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
