"""account default timezone

Revision ID: 92b6c34e7219
Revises: 2e4c09184e64
Create Date: 2026-09-17 12:35:11.688148

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '92b6c34e7219'
down_revision: str | None = '2e4c09184e64'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('default_timezone', sqlmodel.sql.sqltypes.AutoString(), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'default_timezone')
    # ### end Alembic commands ###
