"""player rollouts

Revision ID: 9343c6a18fd3
Revises: 514695584cc7
Create Date: 2026-09-10 22:14:27.341062

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '9343c6a18fd3'
down_revision: str | None = '514695584cc7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rollouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('apk_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rollouts_scheduled_at'), 'player_rollouts', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_rollouts_scheduled_at'), table_name='player_rollouts')
    op.drop_table('player_rollouts')
    # ### end Alembic commands ###
