"""playlist fit, enabled and shuffle

Revision ID: 9cfe71e36e53
Revises: d00519ec4dca
Create Date: 2026-09-08 12:36:38.816513

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = '9cfe71e36e53'
down_revision: str | None = 'd00519ec4dca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add three NOT NULL columns to tables that may already hold rows.

    Autogenerate wrote these without a server_default, which works only on an empty table —
    Postgres refuses to add a NOT NULL column to existing rows with nothing to put in it.
    The fix is the standard two-step: add WITH a default so existing rows are backfilled,
    then drop the default so the schema matches the model and `alembic check` stays clean
    (env.py has compare_server_default=True, so a lingering default reads as drift).
    """
    op.add_column(
        "playlist_items",
        sa.Column(
            "fit",
            sa.Enum("contain", "cover", "stretch", name="itemfit", native_enum=False),
            nullable=False,
            server_default="contain",
        ),
    )
    op.add_column(
        "playlist_items",
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        "playlists",
        sa.Column("shuffle", sa.Boolean(), nullable=False, server_default=sa.false()),
    )

    op.alter_column("playlist_items", "fit", server_default=None)
    op.alter_column("playlist_items", "is_enabled", server_default=None)
    op.alter_column("playlists", "shuffle", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'shuffle')
    op.drop_column('playlist_items', 'is_enabled')
    op.drop_column('playlist_items', 'fit')
    # ### end Alembic commands ###
