"""device update status

Revision ID: b7d1e4c2a9f0
Revises: 92b6c34e7219
Create Date: 2026-09-17 15:10:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = 'b7d1e4c2a9f0'
down_revision: str | None = '92b6c34e7219'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # What a screen reports while it installs a player build — see Device.update_state.
    op.add_column(
        'devices',
        sa.Column(
            'update_state',
            sa.Enum('downloading', 'installing', 'installed', 'failed', native_enum=False, name='deviceupdatestate'),
            nullable=True,
        ),
    )
    op.add_column('devices', sa.Column('update_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('devices', sa.Column('update_progress_pct', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('update_detail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('devices', sa.Column('update_reported_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('devices', 'update_reported_at')
    op.drop_column('devices', 'update_detail')
    op.drop_column('devices', 'update_progress_pct')
    op.drop_column('devices', 'update_version')
    op.drop_column('devices', 'update_state')
