"""device events, play events, storage quota

Revision ID: d0b5419c0914
Revises: ef69be697061
Create Date: 2026-09-08 18:02:43.740832

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = 'd0b5419c0914'
down_revision: str | None = 'ef69be697061'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.Enum('info', 'error', name='eventlevel', native_enum=False), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_events_account_id'), 'device_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_device_events_created_at'), 'device_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_events_device_id'), 'device_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_events_level'), 'device_events', ['level'], unique=False)
    op.create_table('play_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_events_account_id'), 'play_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_play_events_device_id'), 'play_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_play_events_started_at'), 'play_events', ['started_at'], unique=False)
    op.add_column('accounts', sa.Column('storage_quota_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'storage_quota_bytes')
    op.drop_index(op.f('ix_play_events_started_at'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_device_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_account_id'), table_name='play_events')
    op.drop_table('play_events')
    op.drop_index(op.f('ix_device_events_level'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_device_id'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_created_at'), table_name='device_events')
    op.drop_index(op.f('ix_device_events_account_id'), table_name='device_events')
    op.drop_table('device_events')
    # ### end Alembic commands ###
