"""playlist item rotation degrees

Revision ID: ebb51f2a655b
Revises: 31c427eb08e7
Create Date: 2026-09-10 14:51:12.999354

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = 'ebb51f2a655b'
down_revision: str | None = '31c427eb08e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOT NULL on a table that may already hold rows — same two-step as has_audio: add with
    # a default so existing rows backfill, then drop the default so the schema matches the
    # model (env.py has compare_server_default=True).
    op.add_column(
        'playlist_items',
        sa.Column('rotation_degrees', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('playlist_items', 'rotation_degrees', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'rotation_degrees')
    # ### end Alembic commands ###
