"""schedules and device timezone

Revision ID: ef69be697061
Revises: 9cfe71e36e53
Create Date: 2026-09-08 17:01:26.321313

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# SQLModel emits sqlmodel.sql.sqltypes.AutoString for str columns, so an
# autogenerated migration needs this import or it fails with NameError at upgrade.
import sqlmodel


revision: str = 'ef69be697061'
down_revision: str | None = '9cfe71e36e53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('playlist_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('days_of_week', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_account_id'), 'schedules', ['account_id'], unique=False)
    op.create_index(op.f('ix_schedules_device_id'), 'schedules', ['device_id'], unique=False)
    # NOT NULL on a table that already has rows: add WITH a default so existing devices
    # backfill to UTC, then drop the default so the schema matches the model and
    # `alembic check` stays clean (env.py sets compare_server_default=True).
    op.add_column(
        'devices',
        sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False,
                  server_default='UTC'),
    )
    op.alter_column('devices', 'timezone', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'timezone')
    op.drop_index(op.f('ix_schedules_device_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_account_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
